<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Site</title>
    <link rel="stylesheet" type="text/css" href="/WWWEndProject/public/css/navigation.css">
    <link rel="stylesheet" type="text/css" href="/WWWEndProject/public/css/main.css">
    <script src="/WWWEndProject/public/js/jquery-2.2.0.min.js"></script>
    <script src="/WWWEndProject/public/js/main.js"></script>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
</head>
<body>
   <div class="header">
        <?php $this->renderTemplateOnDemand('helptemplates/navigation', true)?>
   </div>
   <div class="body">
   		<?php $this->renderTemplate();?>
   		<?php $this->renderTemplateOnDemand('helptemplates/chatfields', true)?>
   </div>
   <div class="footer">
   </div>
</body>
</html>